[package]
name = "shrt"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
open = "1.0"
confy = "1.0"
color-print = "0.3.7"
colored = "3.0.0"
